from sage.all import GF, ceil

def BSGS(p, g, h, ell):
    '''
    Baby-step giant-step algorithm to solve h = g^x (mod p).
    Inputs:
        p (int): Prime modulus
        g (int): Element of Z/pZ
        h (int): Target value
        ell (int): Order of g in Z/pZ
    Returns:
        x (int): Discrete log solution
        None: If no solution is found
    '''
    # Check if h is in the subgroup generated by g
    if pow(h, ell, p) != 1:
        print('Error: h not in subgroup generated by g')
        return None

    B = 50 # Maximum bit length for ell
    if ell >= 2 ** B: # Check ell is within bound
        print(f'Input Error: Group order larger than 2^{B}')
        return None
    
    F = GF(p) # Initialize finite field
    g = F(g) # Convert input to field element

    # Number of steps required to cover the solution space
    num_steps = ceil(ell ** 0.5)
    # Precompute baby steps and store in a hash table for quick access
    baby_steps = {int(g ** i): i for i in range(num_steps)}
    
    giant_step = g ** -num_steps # Compute the giant step multiplier
    gs_j = F(h) # Set inital giant step as field element

    # Iterate over giant steps
    for j in range(num_steps):
        # Check for a match in baby steps
        if gs_j in baby_steps: 
            return (j * num_steps) + baby_steps[gs_j] # Return x = j * numsteps + i
        gs_j *= giant_step # Compute next giant step

    # If no solution is found raise an error
    print('Error: Solution Not Found')
    return None