from sage.all import GF, log, exp, sqrt, Matrix, prime_range, vector, factor, ZZ, crt

def factor_to_base(p, n_initial, blank_factorbase):
    """
    Tries to factorize n_initial positively then negatively over a given set of factors in Z/pZ
    Inputs:
        p (int): Prime modulus
        n_initial (int): Number in Z/pZ to be factored
        blank_factorbase (dict): {f1: 0, f2:0, ...} for positive prime factors
    Returns:
        (bool): Whether the number is factorable/smooth
        (list): Exponents of each factor in factorization or empty list
            Prepend 0 if factored positively (-1^0)
            Prepend 1 if factored negatively (-1^1)
    """
    def factorize(n):
        factors = dict(blank_factorbase) # Create copy of blank factorbase
        for f in factors: # For each prime factor
            while n % f == 0: # If factor divides n
                factors[f] += 1 # Increase exponent count
                n //= f # Decrease n
        return n == 1, factors # Return is_smooth, filled in factorbase
    
    # Tries to factorize n * (-1)^0
    is_positive_smooth, exponents = factorize(n_initial)
    if is_positive_smooth:
        return True, [0] + list(exponents.values())
    
    # Tries to factorize n * (-1)^1
    is_negative_smooth, exponents = factorize(p - n_initial)
    if is_negative_smooth:
        return True, [1] + list(exponents.values())
    
    return False, [] # Unsuccessful


def IC(p, g, h):
    '''
    Classical index calculus algorithm to solve h = g^x (mod p).
    Inputs:
        p (int): Prime modulus
        g (int): Generator of Z/pZ
        h (int): Target value
    Returns:
        x (int): Discrete log solution
        None: If no solution is found
    Notes:
        Factor base smoothness is determined by the bound B.
        Failure may occur if insufficient smooth relations are generated.
    '''

    P = GF(p) # Initialize finite field
    g, h = P(g), P(h) # Convert inputs to field elements

    # Multiplicative order of generator g in Z/pZ
    ell = g.multiplicative_order()
    ell_factors = factor(ell)
    
    # Check if h is in the subgroup generated by g
    if h ** ell != 1:
        print('Error: h not in subgroup generated by g')
        return None
    
    # Formula to calculate reasonable bound B for factorbase, based on the density of smooth integers
    B = int(exp(0.5 * sqrt(log(p) * log(log(p)))))

    # FACTORBASE: {-1, f1, f2, ..., fb} for f1, ..., fb in F
    F = prime_range(B + 1) # Factorbase of primes up to and including B
    F_blank = {f: 0 for f in F} # Blank dictionary for factorbase of primes
    F_len = len(F) + 1 # Adjust F symbollically to include -1 as a factor

    max_relations = F_len * 1.25 # How many relations to collect

    relations = [] # Collects the exponents in the factorization of B-smooth integers
    indices = [] # Collects corresponding k such that g^k is B-smooth

    # Iterates until it is likely we have F_len linearly independent relations
    while len(relations) <  max_relations:
        k = ZZ.random_element(p) # Fast random integer from Z/pZ
        g_k = ZZ(g ** k) # Computes g^k (mod p)

        # Factors g^k with respect to factorbase to determine if g^k is B-smooth
        is_smooth, factor_exponents = factor_to_base(p, g_k, F_blank)

        if is_smooth:
            relations.append(factor_exponents) # Save smooth factorization
            indices.append(ZZ(k)) # Save smooth element k

    # Collects remainders/moduli for Chinese Remainder Theorem
    remainders = [] 
    moduli = [] 
    # Convert our relations into system of linear equations: Ax=b
    # Where x = (dlog(f_1), ..., dlog(f_n)) for f_1, ..., f_n in factorbase
    A = Matrix(relations)
    b = vector(indices)

    # Solves Ax=b (mod q^e) for each prime power factor
    for q, e in ell_factors:
        Q = GF(q) # Finite field for q
        Amodq = A.change_ring(Q) # A (mod q)
        bmodq = b.change_ring(Q) # b (mod q)

        # Calculate rank/independence of linear system
        A_rank = Amodq.rank()
        Ab_rank = Amodq.augment(bmodq).rank()

        # Check the linear system is solvable (mod q)
        if A_rank < F_len or A_rank != Ab_rank: 
            print('Error: No Solution Found, Try again.')
            return None

        # Solve system for vector x (mod q)
        x = Amodq.solve_right(bmodq)
        x = x.change_ring(ZZ)
        
        # Use Hensel's lemma to lift solutions (mod q) to (mod q^e)
        for i in range(1, e):
            q_i = q ** i # Current modulus
            q_ii = q_i * q # Next modulus
            # Compute residual vector for each i
            residual = ((A * x) - b) % q_ii
            residual = residual / q_i
            residual = residual.change_ring(Q)
            # Compute correction vector for each i
            delta_x = Amodq.solve_right(-residual)
            delta_x = delta_x.change_ring(ZZ)
            # x_i+1 = x_i + (delta_x_i * q_i)
            x = x + (delta_x * q_i) 

        remainders.append(x) # Saves vector x (mod q^e)
        moduli.append(q**e) # Saves q^e

    # Chinese Remainder Theorem to combine:
    # x_1 (mod q_1^e_1) ... x_n (mod q_n^e_n) = x (mod phi) for vectors x_1 ... x_n
    dlogs = [crt(list(x), moduli) for x in zip(*remainders)] 
    
    while True:
        j = ZZ.random_element(p) # Random element from Z/pZ
        h_j = ZZ(h * (g ** j)) # Computes h * (g ** j) (mod p)

        # Try to represent h in terms of dlogs by checking if h*g^k is B-smooth
        is_smooth, factor_exponents = factor_to_base(p, h_j, F_blank)

        if is_smooth:
            # Calculate and return dlog(h) using dlog(f_1) ... dlog(f_n)
            dlogh = sum(dl * e for dl, e in zip(dlogs, factor_exponents)) - ZZ(j)
            return int(dlogh % ell)