"""Pollard's rho algorithm for the discrete logarithm problem.

Floyd's cycle detection over a pseudorandom walk; O(sqrt(ell)) time with
O(1) space, unlike BSGS's O(sqrt(ell)) space. Only valid for prime-order
subgroups -- reduce composite-order instances via Pohlig-Hellman first.
"""

from sage.all import GF, is_prime, ZZ

def pollard_rho(p, g, h, ell):
    """
    Pollard's rho algorithm to solve h = g^x (mod p).
    Inputs:
        p (int): Prime modulus
        g (int): Generator of prime order subgroup of Z/pZ
        h (int): Target value
        ell (int): Prime order of g in Z/pZ
    Returns:
        x (int): Discrete log solution
        None: If no solution is found
    """

    # Ensure ell is prime
    if not is_prime(ell):
        print('Error: Group Order Not Prime')
        return None
    # Check if h is in the subgroup generated by g
    if pow(h, ell, p) != 1:
        print('Error: h not in subgroup generated by g')
        return None

    # Define step function for pseudorandom walk with x_i+1, a_i+1, b_i+1 = step(x_i, a_i, b_i)
    step = {
        0: lambda x, a, b: (x * g, a + 1, b), # x <- S_1
        1: lambda x, a, b: (x * h, a, b + 1), # x <- S_2
        2: lambda x, a, b: (x * x, 2 * a, 2 * b) # x <- S_3
    }

    P = GF(p) # Initialize finite field for whole group
    L = GF(ell) # Initialize finite field for subgroup

    # Inital tortoise / hare variables
    xi, ai, bi = Xi, Ai, Bi = P(1), L(0), L(0)

    # Use Floyd's cycle finding algorithm to find collision between tortoise and hare
    for i in range(1, ell):
        # Step tortoise once
        xi, ai, bi = step[ZZ(xi) % 3](xi, ai, bi)
        # Step hare twice
        Xi, Ai, Bi = step[ZZ(Xi) % 3](Xi, Ai, Bi)
        Xi, Ai, Bi = step[ZZ(Xi) % 3](Xi, Ai, Bi)

        # Check for collision
        if xi == Xi:
            # Ensure collision is valid
            if bi == Bi:
                print('Error: Invalid Collision')
                return None

            # Compute the discrete logarithm
            rhs = Ai - ai
            lhs = bi - Bi
            return int(rhs / lhs)

    print('Error: No Collision Found')
    return None